name: dbt workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run dbt
        uses: dbt-labs/dbt-action@v1.0.0
        with:
          dbt-version: 1.9.4
          commands: |
            dbt deps
            dbt run
            dbt test
          profiles-dir: click_lease/.dbt
        env:
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_ROLE: ${{ secrets.DBT_ROLE }}
          DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
          DBT_WAREHOUSE: ${{ secrets.DBT_WAREHOUSE }}
          DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
