name: dbt prod

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-snowflake==1.9.4

      - name: dbt deps
        run: dbt deps --profiles-dir .dbt
        working-directory: click_lease
        env:
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_ROLE: ${{ secrets.DBT_ROLE }}
          DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
          DBT_WAREHOUSE: ${{ secrets.DBT_WAREHOUSE }}
          DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}

      - name: dbt run
        run: dbt run --profiles-dir .dbt
        working-directory: click_lease
        env:
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_ROLE: ${{ secrets.DBT_ROLE }}
          DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
          DBT_WAREHOUSE: ${{ secrets.DBT_WAREHOUSE }}
          DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}

      - name: dbt test
        run: dbt test --profiles-dir .dbt
        working-directory: click_lease
        env:
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_ROLE: ${{ secrets.DBT_ROLE }}
          DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
          DBT_WAREHOUSE: ${{ secrets.DBT_WAREHOUSE }}
          DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
